// Generated by commsdsl2tools_qt v6.3.0

#pragma once

#include <tuple>
#include <QtCore/QVariantList>
#include "cc_tools_qt/TransportMessageBase.h"
#include "cc_tools_qt_plugin/cc_demo1/options/DefaultOptions.h"
#include "cc_demo1/frame/Frame.h"
#include "cc_tools_qt_plugin/cc_demo1/Message.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo1
{

namespace frame
{

struct FrameTransportMessageFields
{
    using All =
        std::tuple<
            ::cc_demo1::frame::FrameLayers<cc_tools_qt_plugin::cc_demo1::options::DefaultOptions>::SyncMembers::Sync,
            ::cc_demo1::frame::FrameLayers<cc_tools_qt_plugin::cc_demo1::options::DefaultOptions>::SizeMembers::Size,
            ::cc_demo1::field::MsgId<cc_tools_qt_plugin::cc_demo1::options::DefaultOptions>,
            ::cc_demo1::frame::FrameLayers<cc_tools_qt_plugin::cc_demo1::options::DefaultOptions>::Data::Field,
            ::cc_demo1::frame::FrameLayers<cc_tools_qt_plugin::cc_demo1::options::DefaultOptions>::ChecksumMembers::Checksum
        >;
    static const QVariantList& props();
};

class FrameTransportMessage : public
    cc_tools_qt::TransportMessageBase<
        cc_tools_qt_plugin::cc_demo1::Message,
        FrameTransportMessageFields::All
    >
{
protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override;
    virtual comms::ErrorStatus readImpl(ReadIterator& iter, std::size_t len) override;
};

} // namespace frame

} // namespace cc_demo1

} // namespace cc_tools_qt_plugin
