// Generated by commsdsl2tools_qt v8.0.0

/// @file
/// @brief Contains definition of the default options for plugin.

#pragma once

#include "cc_demo1/options/AllMessagesDynMemMsgFactoryDefaultOptions.h"
#include "cc_demo1/options/DefaultOptions.h"
#include "cc_tools_qt_plugin/cc_demo1/Version.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo1
{

namespace options
{

using DefaultOptions =
    ::cc_demo1::options::AllMessagesDynMemMsgFactoryDefaultOptionsT<
        ::cc_demo1::options::DefaultOptions
    >;

} // namespace options

} // namespace cc_demo1

} // namespace cc_tools_qt_plugin
