// Generated by commsdsl2tools_qt v6.3.3

#pragma once

#include <tuple>
#include "cc_tools_qt_plugin/cc_demo1/message/Ack.h"
#include "cc_tools_qt_plugin/cc_demo1/message/Bitfields.h"
#include "cc_tools_qt_plugin/cc_demo1/message/Datas.h"
#include "cc_tools_qt_plugin/cc_demo1/message/Enums.h"
#include "cc_tools_qt_plugin/cc_demo1/message/Floats.h"
#include "cc_tools_qt_plugin/cc_demo1/message/Lists.h"
#include "cc_tools_qt_plugin/cc_demo1/message/Optionals.h"
#include "cc_tools_qt_plugin/cc_demo1/message/ScaledInts.h"
#include "cc_tools_qt_plugin/cc_demo1/message/Sets.h"
#include "cc_tools_qt_plugin/cc_demo1/message/SimpleInts.h"
#include "cc_tools_qt_plugin/cc_demo1/message/Strings.h"
#include "cc_tools_qt_plugin/cc_demo1/message/Variants.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo1
{

namespace input
{

using AllMessages =
    std::tuple<
        cc_tools_qt_plugin::cc_demo1::message::Ack,
        cc_tools_qt_plugin::cc_demo1::message::SimpleInts,
        cc_tools_qt_plugin::cc_demo1::message::ScaledInts,
        cc_tools_qt_plugin::cc_demo1::message::Floats,
        cc_tools_qt_plugin::cc_demo1::message::Enums,
        cc_tools_qt_plugin::cc_demo1::message::Sets,
        cc_tools_qt_plugin::cc_demo1::message::Bitfields,
        cc_tools_qt_plugin::cc_demo1::message::Strings,
        cc_tools_qt_plugin::cc_demo1::message::Datas,
        cc_tools_qt_plugin::cc_demo1::message::Lists,
        cc_tools_qt_plugin::cc_demo1::message::Optionals,
        cc_tools_qt_plugin::cc_demo1::message::Variants
    >;

} // namespace input

} // namespace cc_demo1

} // namespace cc_tools_qt_plugin
