// Generated by commsdsl2tools_qt v7.3.0

#include "Bitfields.h"

#include "cc_demo1/message/Bitfields.h"
#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_demo1/Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_demo1
{

namespace message
{

class BitfieldsImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_demo1::Message,
        ::cc_demo1::message::Bitfields,
        BitfieldsImpl
    >
{
public:
    BitfieldsImpl() = default;
    BitfieldsImpl(const BitfieldsImpl&) = default;
    BitfieldsImpl(BitfieldsImpl&&) = default;
    virtual ~BitfieldsImpl() = default;
    BitfieldsImpl& operator=(const BitfieldsImpl&) = default;
    BitfieldsImpl& operator=(BitfieldsImpl&&) = default;
};

Bitfields::Bitfields() : m_pImpl(new BitfieldsImpl) {}
Bitfields::~Bitfields() = default;

Bitfields& Bitfields::operator=(const Bitfields& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Bitfields& Bitfields::operator=(Bitfields&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* Bitfields::nameImpl() const
{
    return m_pImpl->name();
}

bool Bitfields::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong Bitfields::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString Bitfields::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void Bitfields::resetImpl()
{
    m_pImpl->reset();
}

bool Bitfields::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const Bitfields*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool Bitfields::isValidImpl() const
{
    return m_pImpl->isValid();
}

Bitfields::DataSeq Bitfields::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool Bitfields::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

Bitfields::Ptr Bitfields::cloneImpl() const
{
    ImplPtr impl(static_cast<BitfieldsImpl*>(m_pImpl->clone().release()));
    return Ptr(new Bitfields(std::move(impl)));
}

void Bitfields::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

Bitfields::DataSeq Bitfields::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

Bitfields::FieldsList Bitfields::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

Bitfields::FieldsList Bitfields::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

Bitfields::Bitfields(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_demo1

} // namespace Message

} // namespace cc_tools_qt_plugin
