// Generated by commsdsl2tools_qt v7.0.0

#include "Optionals.h"

#include "cc_demo1/message/Optionals.h"
#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_demo1/Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_demo1
{

namespace message
{

class OptionalsImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_demo1::Message,
        ::cc_demo1::message::Optionals,
        OptionalsImpl
    >
{
public:
    OptionalsImpl() = default;
    OptionalsImpl(const OptionalsImpl&) = default;
    OptionalsImpl(OptionalsImpl&&) = default;
    virtual ~OptionalsImpl() = default;
    OptionalsImpl& operator=(const OptionalsImpl&) = default;
    OptionalsImpl& operator=(OptionalsImpl&&) = default;
};

Optionals::Optionals() : m_pImpl(new OptionalsImpl) {}
Optionals::~Optionals() = default;

Optionals& Optionals::operator=(const Optionals& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Optionals& Optionals::operator=(Optionals&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* Optionals::nameImpl() const
{
    return m_pImpl->name();
}

bool Optionals::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong Optionals::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString Optionals::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void Optionals::resetImpl()
{
    m_pImpl->reset();
}

bool Optionals::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const Optionals*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool Optionals::isValidImpl() const
{
    return m_pImpl->isValid();
}

Optionals::DataSeq Optionals::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool Optionals::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

Optionals::Ptr Optionals::cloneImpl() const
{
    ImplPtr impl(static_cast<OptionalsImpl*>(m_pImpl->clone().release()));
    return Ptr(new Optionals(std::move(impl)));
}

void Optionals::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

Optionals::DataSeq Optionals::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

Optionals::FieldsList Optionals::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

Optionals::FieldsList Optionals::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

Optionals::Optionals(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_demo1

} // namespace Message

} // namespace cc_tools_qt_plugin
