// Generated by commsdsl2tools_qt v7.1.0

#include "Variants.h"

#include "cc_demo1/message/Variants.h"
#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_demo1/Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_demo1
{

namespace message
{

class VariantsImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_demo1::Message,
        ::cc_demo1::message::Variants,
        VariantsImpl
    >
{
public:
    VariantsImpl() = default;
    VariantsImpl(const VariantsImpl&) = default;
    VariantsImpl(VariantsImpl&&) = default;
    virtual ~VariantsImpl() = default;
    VariantsImpl& operator=(const VariantsImpl&) = default;
    VariantsImpl& operator=(VariantsImpl&&) = default;
};

Variants::Variants() : m_pImpl(new VariantsImpl) {}
Variants::~Variants() = default;

Variants& Variants::operator=(const Variants& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Variants& Variants::operator=(Variants&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* Variants::nameImpl() const
{
    return m_pImpl->name();
}

bool Variants::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong Variants::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString Variants::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void Variants::resetImpl()
{
    m_pImpl->reset();
}

bool Variants::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const Variants*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool Variants::isValidImpl() const
{
    return m_pImpl->isValid();
}

Variants::DataSeq Variants::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool Variants::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

Variants::Ptr Variants::cloneImpl() const
{
    ImplPtr impl(static_cast<VariantsImpl*>(m_pImpl->clone().release()));
    return Ptr(new Variants(std::move(impl)));
}

void Variants::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

Variants::DataSeq Variants::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

Variants::FieldsList Variants::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

Variants::FieldsList Variants::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

Variants::Variants(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_demo1

} // namespace Message

} // namespace cc_tools_qt_plugin
