// Generated by commsdsl2tools_qt v6.3.0

#include "Plugin_CC_Demo1.h"

#include "Protocol_CC_Demo1.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo1
{

namespace plugin
{

Plugin_CC_Demo1::Plugin_CC_Demo1() :
    m_protocol(new Protocol_CC_Demo1())
{
    pluginProperties()
        .setProtocolCreateFunc(
            [this]() noexcept -> cc_tools_qt::ProtocolPtr
            {
                return m_protocol;
            })
    ;
}

Plugin_CC_Demo1::~Plugin_CC_Demo1() = default;

} // namespace plugin

} // namespace cc_demo1

} // namespace cc_tools_qt_plugin
