// Generated by commsdsl2tools_qt v8.0.0

#pragma once

#include "cc_tools_qt/ToolsProtocol.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo1
{

namespace plugin
{

class Protocol_CC_Demo1 : public cc_tools_qt::ToolsProtocol
{
    using Base = cc_tools_qt::ToolsProtocol;
public:
    Protocol_CC_Demo1();
    virtual ~Protocol_CC_Demo1();

protected:
    virtual const QString& nameImpl() const override;
};

} // namespace plugin

} // namespace cc_demo1

} // namespace cc_tools_qt_plugin
