// Generated by commsdsl2tools_qt v6.3.4

#pragma once

#include "cc_demo1/Message.h"
#include "cc_tools_qt/MessageBase.h"
#include "cc_tools_qt_plugin/cc_demo1/Version.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo1
{

using Message =
    cc_tools_qt::MessageBase<
        ::cc_demo1::Message
    >;

} // namespace cc_demo1

} // namespace cc_tools_qt_plugin
