// Generated by commsdsl2tools_qt v6.3.2

#pragma once

#include <QtCore/QVariantMap>

namespace cc_tools_qt_plugin
{

namespace cc_demo1
{

namespace field
{

QVariantMap createProps_lat(const char* name, bool serHidden = false);

} // namespace field

} // namespace cc_demo1

} // namespace cc_tools_qt_plugin
