// Generated by commsdsl2tools_qt v6.3.4

#include "MsgId.h"

#include "cc_demo1/field/MsgId.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_demo1/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo1
{

namespace field
{

QVariantMap createProps_msgId(const char* name, bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_demo1::field::MsgId<cc_tools_qt_plugin::cc_demo1::options::DefaultOptions>;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(name)
            .serialisedHidden(serHidden)
            .add("Ack", 0)
            .add("SimpleInts", 1)
            .add("ScaledInts", 2)
            .add("Floats", 3)
            .add("Enums", 4)
            .add("Sets", 5)
            .add("Bitfields", 6)
            .add("Strings", 7)
            .add("Datas", 8)
            .add("Lists", 9)
            .add("Optionals", 10)
            .add("Variants", 11)
            .asMap();
}

} // namespace field

} // namespace cc_demo1

} // namespace cc_tools_qt_plugin
